### ISSUE TITLE
issues running the project locally

### ISSUE THREAD

**Issue by AJFunk** [pastudan/altfolio-live#2]
I've been using this app for a few weeks now and was hoping to contribute, but I'm having some issues getting the project running locally. Can you add some documentation on how to get it started?

**Comment by pastudan** [comment]
Hi AJ! Thanks for the interest in contributing. I've added some documentation to the [README](https://github.com/pastudan/altfolio-live/blob/master/README.md) with https://github.com/pastudan/altfolio-live/pull/3. See if that helps, and let me know if there's anything else I can clarify. 🍻
